### ISSUE TITLE
Add a `strip_str` method

### ISSUE THREAD

**Issue by sunshowers** [luser/strip-ansi-escapes#10]
A UTF-8 string with ANSI escapes stripped should continue to be valid UTF-8. So we should be able to define (after #9):

```rust
fn strip_str(s: impl AsRef<str>) -> String {
    let bytes = strip(s.as_ref());
    String::from_utf8(bytes).expect("UTF-8 string with ANSI escapes removed is valid UTF-8")
}
```

What do you think?

**Comment by sunshowers** [comment]
(Happy to submit patches for both the issues I filed! :) )

**Comment by luser** [comment]
This seems very reasonable. I guess an alternate approach would be something like `fn strip<T>(t: T) -> <T as ToOwned>::Owned where T: AsRef<u8>, T: ToOwned {}` ? That might not be worth the headaches, though. :)

**Comment by sunshowers** [comment]
I'm not sure the invariant can be upheld for any arbitrary T, just for strings.
