### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by benesch** [luser/strip-ansi-escapes#15]
It'd be awesome to get a new version published with #14 included, whenever you have a second, @luser!

**Comment by sourcefrog** [comment]
It would be handy to have `strip_str` from #11 in a release, too.

**Comment by benesch** [comment]
Gentle ping on this, @luser!

**Comment by luser** [comment]
Done: https://crates.io/crates/strip-ansi-escapes/0.1.2

Sorry, I kept forgetting about this. 🤦
