### ISSUE TITLE
0.1.1 -> 0.1.2 is a breaking change

### ISSUE THREAD

**Issue by yannham** [luser/strip-ansi-escapes#17]
Hi, and first thanks for the work on strip-ansi-escapes! We use it as a dependency of the [Nickel programming language](https://github.com/tweag/nickel/). However, the recent update from 0.1.1 to 0.1.2 broke our build in some situations. Indeed, this update changed the interface of the public method `strip` (which doesn't return a `Result<_, _>` anymore, but just a `Vec<u8>`).

Changing the interface of a public method is a breaking change, and mandates an update to 0.2.0, as per semantic versioning. I would advise to yank the 0.1.2 version and to release a 0.2.0 version with the same content as 0.1.2.

**Comment by jnicholls** [comment]
I want to mirror my appreciation for your work on strip-ansi-escapes! Thank you.

FWIW, this breaks the compilation of `junit-report` which is a dependency of `cargo2junit` and how I discovered this breaking change.

The suggestion above from @yannham is absolutely correct and I appreciate your swift action on this @luser, thanks!

**Comment by sdroege** [comment]
FWIW, this also breaks compilation of everything that depends on the `cargo` crate.

**Comment by aseure** [comment]
Release `0.1.2` includes this PR https://github.com/luser/strip-ansi-escapes/pull/11 which seems to be the problematic one.

**Comment by luser** [comment]
Sorry about that! I did not do the due diligence here. I just yanked 0.1.2, I'll merge #18 and publish 0.2.0 to get things back on track.

**Comment by luser** [comment]
https://crates.io/crates/strip-ansi-escapes/0.2.0

**Comment by philbucher** [comment]
Thanks for the quick fix, this is very much appreciated!
